"""
HTML report generation module.

Generates standalone HTML reports with embedded charts (base64),
measurement summaries, congestion analysis, and recommendations.
"""

import base64
import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from utils import logger


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Network Performance Report</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: #f5f5f5;
            color: #333;
            line-height: 1.6;
        }}
        .container {{ max-width: 1200px; margin: 0 auto; padding: 20px; }}
        header {{
            background: linear-gradient(135deg, #1a237e, #283593);
            color: white;
            padding: 30px;
            border-radius: 8px;
            margin-bottom: 24px;
        }}
        header h1 {{ font-size: 28px; margin-bottom: 8px; }}
        header .meta {{ opacity: 0.85; font-size: 14px; }}
        .card {{
            background: white;
            border-radius: 8px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.08);
            margin-bottom: 24px;
            overflow: hidden;
        }}
        .card-header {{
            background: #f8f9fa;
            padding: 16px 24px;
            border-bottom: 1px solid #e9ecef;
            font-size: 18px;
            font-weight: 600;
        }}
        .card-body {{ padding: 24px; }}
        .metrics-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 16px;
        }}
        .metric {{
            background: #f8f9fa;
            padding: 16px;
            border-radius: 6px;
            text-align: center;
        }}
        .metric .value {{
            font-size: 24px;
            font-weight: 700;
            color: #1a237e;
        }}
        .metric .label {{
            font-size: 12px;
            color: #666;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            margin-top: 4px;
        }}
        .plot-container {{
            text-align: center;
            margin: 16px 0;
        }}
        .plot-container img {{
            max-width: 100%;
            border-radius: 4px;
        }}
        .severity-mild {{ color: #f9a825; }}
        .severity-moderate {{ color: #ff6f00; }}
        .severity-severe {{ color: #c62828; font-weight: bold; }}
        .severity-none {{ color: #2e7d32; }}
        .recommendation {{
            background: #e3f2fd;
            border-left: 4px solid #1565c0;
            padding: 12px 16px;
            margin: 8px 0;
            border-radius: 0 4px 4px 0;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 8px 0;
        }}
        th, td {{
            padding: 10px 16px;
            text-align: left;
            border-bottom: 1px solid #e9ecef;
        }}
        th {{ background: #f8f9fa; font-weight: 600; font-size: 13px; }}
        td {{ font-size: 14px; }}
        footer {{
            text-align: center;
            padding: 24px;
            color: #999;
            font-size: 13px;
        }}
    </style>
</head>
<body>
<div class="container">
    <header>
        <h1>Network Performance Report</h1>
        <div class="meta">
            Generated: {timestamp}<br>
            Target: {target_host}
        </div>
    </header>

    {sections}

    <footer>
        Generated by Network Performance Measurement Toolkit
    </footer>
</div>
</body>
</html>"""


class ReportGenerator:
    """
    Generates comprehensive HTML reports from measurement results.

    Combines measurement data, statistical analysis, plot images,
    and congestion analysis into a single standalone HTML file.

    Usage:
        gen = ReportGenerator()
        gen.add_latency(latency_result.to_dict())
        gen.add_throughput(throughput_result.to_dict())
        gen.add_plot("latency.png")
        gen.generate("report.html")
    """

    def __init__(self):
        self.sections: List[str] = []
        self.target_host: str = "unknown"
        self.plot_paths: List[str] = []

    def add_latency(self, data: Dict[str, Any]) -> "ReportGenerator":
        """Add latency measurement results to the report."""
        self.target_host = data.get("host", self.target_host)
        html = f"""
    <div class="card">
        <div class="card-header">Latency Measurement</div>
        <div class="card-body">
            <div class="metrics-grid">
                <div class="metric">
                    <div class="value">{data.get('mean_rtt_ms', 0):.2f} ms</div>
                    <div class="label">Mean RTT</div>
                </div>
                <div class="metric">
                    <div class="value">{data.get('median_rtt_ms', 0):.2f} ms</div>
                    <div class="label">Median RTT</div>
                </div>
                <div class="metric">
                    <div class="value">{data.get('min_rtt_ms', 0):.2f} ms</div>
                    <div class="label">Min RTT</div>
                </div>
                <div class="metric">
                    <div class="value">{data.get('max_rtt_ms', 0):.2f} ms</div>
                    <div class="label">Max RTT</div>
                </div>
                <div class="metric">
                    <div class="value">{data.get('p95_rtt_ms', 0):.2f} ms</div>
                    <div class="label">P95 RTT</div>
                </div>
                <div class="metric">
                    <div class="value">{data.get('p99_rtt_ms', 0):.2f} ms</div>
                    <div class="label">P99 RTT</div>
                </div>
                <div class="metric">
                    <div class="value">{data.get('stddev_rtt_ms', 0):.3f} ms</div>
                    <div class="label">Std Dev</div>
                </div>
                <div class="metric">
                    <div class="value">{data.get('loss_percent', 0):.1f}%</div>
                    <div class="label">Packet Loss</div>
                </div>
            </div>
            <p style="margin-top:12px; color:#666;">
                {data.get('successful_probes', 0)} / {data.get('probe_count', 0)} probes successful
                to {data.get('resolved_ip', '')}
            </p>
        </div>
    </div>"""
        self.sections.append(html)
        return self

    def add_jitter(self, data: Dict[str, Any]) -> "ReportGenerator":
        """Add jitter measurement results to the report."""
        html = f"""
    <div class="card">
        <div class="card-header">Jitter Analysis</div>
        <div class="card-body">
            <div class="metrics-grid">
                <div class="metric">
                    <div class="value">{data.get('mean_jitter_ms', 0):.3f} ms</div>
                    <div class="label">Mean Jitter</div>
                </div>
                <div class="metric">
                    <div class="value">{data.get('max_jitter_ms', 0):.3f} ms</div>
                    <div class="label">Max Jitter</div>
                </div>
                <div class="metric">
                    <div class="value">{data.get('p95_jitter_ms', 0):.3f} ms</div>
                    <div class="label">P95 Jitter</div>
                </div>
                <div class="metric">
                    <div class="value">{data.get('rfc3550_jitter_ms', 0):.3f} ms</div>
                    <div class="label">RFC 3550 Jitter</div>
                </div>
                <div class="metric">
                    <div class="value">{data.get('stddev_jitter_ms', 0):.3f} ms</div>
                    <div class="label">Std Dev</div>
                </div>
            </div>
        </div>
    </div>"""
        self.sections.append(html)
        return self

    def add_packet_loss(self, data: Dict[str, Any]) -> "ReportGenerator":
        """Add packet loss measurement results to the report."""
        html = f"""
    <div class="card">
        <div class="card-header">Packet Loss Analysis</div>
        <div class="card-body">
            <div class="metrics-grid">
                <div class="metric">
                    <div class="value">{data.get('loss_percent', 0):.2f}%</div>
                    <div class="label">Total Loss</div>
                </div>
                <div class="metric">
                    <div class="value">{data.get('total_sent', 0)}</div>
                    <div class="label">Packets Sent</div>
                </div>
                <div class="metric">
                    <div class="value">{data.get('total_received', 0)}</div>
                    <div class="label">Packets Received</div>
                </div>
                <div class="metric">
                    <div class="value">{data.get('total_lost', 0)}</div>
                    <div class="label">Packets Lost</div>
                </div>
                <div class="metric">
                    <div class="value">{data.get('max_burst_loss', 0)}</div>
                    <div class="label">Max Burst Loss</div>
                </div>
                <div class="metric">
                    <div class="value">{data.get('mean_loss_burst_length', 0):.1f}</div>
                    <div class="label">Mean Burst Length</div>
                </div>
            </div>
        </div>
    </div>"""
        self.sections.append(html)
        return self

    def add_throughput(self, data: Dict[str, Any]) -> "ReportGenerator":
        """Add throughput measurement results to the report."""
        html = f"""
    <div class="card">
        <div class="card-header">Throughput Benchmark ({data.get('protocol', 'TCP').upper()})</div>
        <div class="card-body">
            <div class="metrics-grid">
                <div class="metric">
                    <div class="value">{data.get('total_throughput', 'N/A')}</div>
                    <div class="label">Total Throughput</div>
                </div>
                <div class="metric">
                    <div class="value">{data.get('mean_throughput', 'N/A')}</div>
                    <div class="label">Mean Throughput</div>
                </div>
                <div class="metric">
                    <div class="value">{data.get('max_throughput', 'N/A')}</div>
                    <div class="label">Max Throughput</div>
                </div>
                <div class="metric">
                    <div class="value">{data.get('min_throughput', 'N/A')}</div>
                    <div class="label">Min Throughput</div>
                </div>
                <div class="metric">
                    <div class="value">{data.get('duration_sec', 0):.1f}s</div>
                    <div class="label">Duration</div>
                </div>
                <div class="metric">
                    <div class="value">{data.get('parallel_streams', 1)}</div>
                    <div class="label">Streams</div>
                </div>
            </div>
        </div>
    </div>"""
        self.sections.append(html)
        return self

    def add_congestion(self, data: Dict[str, Any]) -> "ReportGenerator":
        """Add congestion analysis results to the report."""
        severity_class = f"severity-{data.get('max_severity', 'none')}"

        events_html = ""
        for event in data.get("events", []):
            events_html += f"""
            <tr>
                <td>{event.get('signal', '')}</td>
                <td class="severity-{event.get('severity', 'mild')}">{event.get('severity', '').upper()}</td>
                <td>{event.get('start_index', 0)} - {event.get('end_index', 0)}</td>
                <td>{event.get('duration_samples', 0)}</td>
                <td>{event.get('details', '')}</td>
            </tr>"""

        recs_html = ""
        for rec in data.get("recommendations", []):
            recs_html += f'<div class="recommendation">{rec}</div>'

        html = f"""
    <div class="card">
        <div class="card-header">Congestion Analysis</div>
        <div class="card-body">
            <div class="metrics-grid">
                <div class="metric">
                    <div class="value {severity_class}">{data.get('max_severity', 'none').upper()}</div>
                    <div class="label">Max Severity</div>
                </div>
                <div class="metric">
                    <div class="value">{data.get('total_events', 0)}</div>
                    <div class="label">Total Events</div>
                </div>
                <div class="metric">
                    <div class="value">{data.get('congestion_ratio', 0)*100:.1f}%</div>
                    <div class="label">Congestion Ratio</div>
                </div>
            </div>

            {"<h3 style='margin:16px 0 8px;'>Events</h3><table><thead><tr><th>Signal</th><th>Severity</th><th>Range</th><th>Duration</th><th>Details</th></tr></thead><tbody>" + events_html + "</tbody></table>" if events_html else ""}

            {"<h3 style='margin:16px 0 8px;'>Recommendations</h3>" + recs_html if recs_html else ""}
        </div>
    </div>"""
        self.sections.append(html)
        return self

    def add_plot(self, plot_path: str, title: str = "") -> "ReportGenerator":
        """Embed a plot image (base64-encoded) into the report."""
        if not os.path.exists(plot_path):
            logger.warning("Plot file not found: %s", plot_path)
            return self

        with open(plot_path, "rb") as f:
            img_data = base64.b64encode(f.read()).decode("utf-8")

        display_title = title or Path(plot_path).stem.replace("_", " ").title()
        html = f"""
    <div class="card">
        <div class="card-header">{display_title}</div>
        <div class="card-body">
            <div class="plot-container">
                <img src="data:image/png;base64,{img_data}" alt="{display_title}">
            </div>
        </div>
    </div>"""
        self.sections.append(html)
        self.plot_paths.append(plot_path)
        return self

    def add_raw_data(self, data: Dict[str, Any], title: str = "Raw Data") -> "ReportGenerator":
        """Add a collapsible raw JSON data section."""
        json_str = json.dumps(data, indent=2, default=str)
        html = f"""
    <div class="card">
        <div class="card-header">{title}</div>
        <div class="card-body">
            <details>
                <summary style="cursor:pointer; color:#1565c0;">Click to expand</summary>
                <pre style="background:#f8f9fa; padding:16px; border-radius:4px; overflow-x:auto; margin-top:8px; font-size:12px;">{json_str}</pre>
            </details>
        </div>
    </div>"""
        self.sections.append(html)
        return self

    def generate(self, output_path: str) -> str:
        """
        Generate the final HTML report and write it to disk.

        Returns the absolute path to the generated report.
        """
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        html = HTML_TEMPLATE.format(
            timestamp=timestamp,
            target_host=self.target_host,
            sections="\n".join(self.sections),
        )

        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(html)

        logger.info("HTML report generated: %s", path.resolve())
        return str(path.resolve())
